---
title: "Replication of Rapid Word Learning Under Uncertainty via Cross-Situational Statistics by Yu & Smith (2007, Psychological Science)"
author: "Yawen Dong (yad014@ucsd.edu)"
date: "2024-10-13"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

## Choice of Experiment

I chose to replicate the experiment conducted by Yu and Smith (2007) because it aligns well with my research interests in cognitive development and language acquisition. More specifcally, their research focus on how learners can use cross-situational statistical evidence to learn word-referent mappings provides effective guidance for exploring how children and adults navigate uncertain learning environments and how they apply cognitive strategies to solve complex language learning tasks.

## Stimuli, Procedures, and Potential Challenges

The stimuli required for this experiment includes 54 unique pseudowords generated by a computer program and 54 images of uncommon objects (e.g., facial sauna, canister). These pseudowords and images are used to create various conditions where participants must learn word-referent pairs. Participants are exposed to different settings seperately by varying the number of words and images presented together in each trial. For example, in the 2x2 condition, participants see two objects and hear two pseudowords, while in the 4x4 condition, they are exposed to four words and four objects. Over multiple trials, the participants are expected to track the co-occurrences of the words and objects to learn the correct pairings.

There are two main potential challenges in conducting this experiment. First, managing the high number of trials while ensuring participants’ sustained attention throughout the task can be difficult. Long tasks with many trials may lead to respondent fatigue, which could significantly affect their performance and the reliability of the data. Implementing breaks or designing the experiment to be engaging without overwhelming participants will be essential to maintaining focus and minimizing dropout rates. Secondly, generating suitable pseudowords that maintain linguistically sound requires careful consideration. The pseudowords should not only resemble natural language closely enough to be easily processed by participants, but also remain unfamiliar to prevent prior associations. This balance should be achieved to make sure that the learning of word-referent mappings in the experiment truly reflects cross-situational learning rather than familiarity with word forms.

## Repository Link

<https://github.com/YawenD283/yu2007>

## Original Paper Link

<https://journals.sagepub.com/doi/10.1111/j.1467-9280.2007.01915.x>


## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
